on:
  pull_request_target:
    types: [opened]

name: Pull Request opened

jobs:
  assignToProject:
    name: Assign PullRequest to Project
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json, workflow-details.json
          IGNORE_WARNING: 'true'
      - uses: technote-space/create-project-card-action@v1
        with:
          PROJECT: ${{ env.PROJECT }}
          COLUMN: ${{ env.PR_COLUMN }}
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

  assignAuthor:
    name: Assign author to PR
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/assign-author@v1

  addLabelsByBranch:
    name: PR Labeler
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/pr-labeler-action@v4
