on:
  pull_request:
    types: [opened, synchronize, reopened, closed]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}

name: TOC Generator

jobs:
  toc:
    if: github.event.pull_request.head.user.id == github.event.pull_request.base.user.id
    name: TOC Generator
    runs-on: ubuntu-latest
    timeout-minutes: 3
    steps:
      - uses: technote-space/load-config-action@v1
        with:
          CONFIG_FILENAME: workflow-settings.json, workflow-details.json
          IGNORE_WARNING: 'true'
      - uses: technote-space/toc-generator@v4
        with:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          TARGET_BRANCH_PREFIX: ${{ env.BRANCH_PREFIX }}
          FOLDING: ${{ env.TOC_FOLDING }}
          MAX_HEADER_LEVEL: ${{ env.TOC_MAX_HEADER_LEVEL }}
          TOC_TITLE: ${{ env.TOC_TITLE }}
          CREATE_PR: ${{ env.TOC_CREATE_PR }}
          TARGET_PATHS: ${{ env.TOC_TARGET_PATHS }}
          FOOTER: ${{ env.TOC_FOOTER }}
