name: 'Setup Ruby environment with ruby-build'
description: 'Setup a Ruby environemnt with ruby-build and add it to the PATH'
author: Michael Lang
branding:
  color: red
  icon: code
inputs:
  ruby-version:
    description: 'Ruby version'
    required: true
    default: '2.6.5'
  cache-available:
    description: 'Flag if the Ruby installation is cached'
    required: true
    default: 'false'
runs:
  using: 'node12'
  main: 'dist/index.js'
