name: Auto Assign to Project

on:
  issues:
    types: [opened]

env:
  MY_GITHUB_TOKEN: ${{ secrets.RUBY_GITHUB_TOKEN }}

jobs:
  assign_one_project:
    runs-on: ubuntu-latest
    continue-on-error: true
    name: Assign to One Project
    steps:
    - name: Assign NEW issues and NEW pull requests to project 2
      uses: srggrs/assign-one-project-github-action@1.2.0
      if: github.event.action == 'opened'
      with:
        project: https://github.com/orgs/newrelic/projects/17
