name: PR Review Checklist

on: 
  pull_request:
    types: opened

jobs:
  sidekick_checklist:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checklist
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "PR review checklist:\n
- [ ] Perform code review\n
- [ ] Add performance label\n
- [ ] Perform appropriate level of performance testing\n
- [ ] Confirm all checks passed\n
- [ ] Add version label prior to acceptance"  
