name: PR Sidekick Checklist
on: pull_request
jobs:
  sidekick_checklist:
    name: 
    runs-on: ubuntu-latest
    steps:
      - name: Checklist
        uses: unsplash/comment-on-pr@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          msg: "- [ ] Perform code review
- [ ] Add performance label
- [ ] Perform appropriate level of performance testing
- [ ] Confirm all checks passed
- [ ] Add version label prior to acceptance"
